### ISSUE TITLE
Which Oxalis should we use when sending messages and moving from AS2 to AS4

### ISSUE THREAD

**Issue by odha** [difi/Oxalis-AS4#37]
Which Oxalis should we use when sending messages and moving from AS2 to AS4?

We are currently using 4.0.2 for well over a year now. Works perfectly for sending invoices.

Is that version capacable of sending AS4 messages? Or should we upgrade to the differnt project "Oxalis-AS4"?

Thanks in advance

**Comment by open-gdsn** [comment]
4.0.4 has been released a while ago and the As4 RC's state that they tested compatibility with 4.0.4 and not 4.0.2 (so upgrade). I tested 4.0.4 too and it just works

**Comment by odha** [comment]
Hi @open-gdsn ; thanks for your response.

After we have included 4.0.4 in our project, do we need to alter any configuration files? I can't find release notes from 4.0.4 explaining how to activate sending AS4

**Comment by darklajid** [comment]
@odha - AS4 is implemented as a plugin to Oxalis. You'll run the normal Oxalis distribution as before, but also add AS4 as a transport using the extension points Oxalis provides. The installation guide in the Readme tries to explain how this works for both inbound and standalone.

In other words: 4.0.4 doesn't come with AS4, but 4.0.4 was/is the version the AS4 plugin authors tested with. You were told to upgrade so that you don't run into potential issues that are related to you using a different/older base, but you still need to get AS4 from this repository here.

**Comment by odha** [comment]
Hi guys
We got it up and running for now. Thanks!
