### ISSUE TITLE
Inbound and outbound requires two tomcat instances

### ISSUE THREAD

**Issue by jonassss** [difi/Oxalis-AS4#72]
As mentioned by @FrodeBjerkholt [here](https://github.com/difi/Oxalis-AS4/issues/69#issuecomment-580748513), the inbound and outbound components of oxalis require each of their own instances when paired with AS4.

We think this issue is caused by the no.difi.oxalis.outbound.OxalisOutboundComponent which creates a new dependency injection map when created.
This causes injector objects to be re-created, and because the included libraries in the outbound component do not include all the required components - the inbound handling fails.
In detail the WSS4J classes do not seem to be included correctly in the new injector.

This causes inbound AS4 messages to fail due to a missing algorithm for handling SignedInfo where the reference URI is of type "cid", and for certain transformation types such as http://docs.oasis-open.org/wss/oasis-wss-SwAProfile-1.1#Attachment-Content-Signature-Transform.
This leads to a javax.security.auth.callback.UnsupportedCallbackException.

How to reproduce:
1. Use testbed to deliver AS4 message to your test endpoint.
2. Send AS4 message back with second test. 
3. Resend the first message to your test endpoint.

**Comment by FrodeBjerkholt** [comment]
As @phax mentions in issue #69 - this is a bug in WSS4J: https://issues.apache.org/jira/projects/WSS/issues/WSS-660

**Comment by FrodeBjerkholt** [comment]
I found the following at Red Hat:

##IMPORTANT

Programmatically-created CXF consumers deployed in OSGi environments require special handling to avoid the likelihood of incurring ClassNotFoundExceptions. For each bundle that contains programmatically-created CXF consumers, you need to create a singleton CXF default bus and ensure that all of the bundle's CXF consumers use it. Without this safeguard, one bundle could be assigned the CXF default bus created in another bundle, which could cause the inheriting bundle to fail.
For example, suppose bundle A did not explicitly set a CXF default bus and was assigned the CXF default bus created in bundle B. If the CXF bus in bundle A needed to be configured with additional features (such as SSL or WS-Security) or needed to load certain classes or resources from the application in bundle A, it would fail. This is so because the CXF bus instance sets a thread context class loader (TCCL) as the bundle class loader of the bundle that created it (in this case bundle B). Furthermore, certain frameworks, such as wss4j (implements WS-Security in CXF) use the TCCL to load resources, such as calback handler classes or other property files, from inside the bundle. Because bundle A is assigned bundle B's default CXF bus and it's TCCL, the wss4j layer cannot load the required resources from bundle A, which results in ClassNotFoundException errors.
To create the singleton CXF default bus, insert this code:
```java
BusFactory.setThreadDefaultBus(BusFactory.newInstance().createBus());
```
at the beginning of the main method that creates the service object, as shown in the section called “Example”.
```

**Comment by FrodeBjerkholt** [comment]
The 4.1.6 release and up follows this advice, so the problems might have been fixed?

**Comment by FrodeBjerkholt** [comment]
I am closing the issue. Will reopen if I get new reports.
